config/routes.rb
Depot::Application.routes.draw do

  resources :line_items, :only => [:create]
 
  match 'cart' => 'carts#show', :via => :get
  
  resources :products
  
  get "store" => 'store#index'
  root :to => 'store#index'  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :product
  image_accessor :file

  validates :file, :presence => true
  validates_property :format, :of => :file, :in => [:jpg, :png, :gif]

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :line_items
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true
 
  default_scope :order => 'title'  

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :length => { :minimum => 10 }, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
 
  private

    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
protect_from_forgery

  private
    def current_cart
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
      @cart = current_cart
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  # POST /line_items
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.line_items.build(:product => product)

    if @line_item.save
      redirect_to cart_path, notice: 'Line item was successfully created.'
    else
      render action :new
    end    
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PUT /products/1
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  def render_image_for(image, options={})
    if(image.file_uid)
      options[:resolution] ||= '60x70'
      options[:html] ||= {}
      img = image_tag(image.file.thumb(options[:resolution]).url)
      link_to(img, image.file.url, options[:html])
    end
  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<h2>Your Pragmatic Cart</h2>
<ul>
  <% @cart.line_items.each do |item| %>
    <li><%= item.product.title %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  
  <%= stylesheet_link_tag :application, :nested_form %>
  
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>

</head>

<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">
        <%= link_to "Home", root_url %><br />
        <%= link_to "Products", products_path %><br />
        <%= link_to "Cart", cart_path %>
      <%= Time.now %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_form.html.erb
<%= semantic_nested_form_for(@product, :html => { :multipart => true }) do |f| %>
  <%= f.inputs do %>
    <%= f.input :title , :hint => "Title should be at least 10 characters "%>
    <%= f.input :description , :input_html => { :rows => 10 }%>
    <%= f.input :price %>

    <%= f.semantic_fields_for :images do |image_form| %>
      <%= image_form.link_to_remove "Remove Image" %>
      <%= image_form.input :file, :as => :file, :label => "Image", 
          :hint => "Select    Image" %>
      <%= image_form.input :retained_file, :as => :hidden %> 
    <% end %>   

    <%= f.link_to_add "Add Image", :images %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
  <h1>Listing products</h1>

  <table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
	<% product.images.each do |image| %>
	  <%= image_tag(image.file.url) %>
	<% end %>
      </td>

      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
                 :length => 80) %></dd>
        </dl>
      </td>

      <td class="list_actions">

        <%= link_to 'Show', product %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/>
        <%= link_to 'Destroy', product, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <% @product.images.each do |image| %>
    <%= render_image_for image %>
  <% end %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<h1>Your Pragmatic Catalog</h1>

<% @products.each do |product| %>
  <div class="entry">

    <% product.images.each do |image| %>
      <%= image_tag(image.file.url) %>  
    <% end %>

    <h3><%= product.title %></h3>
    <%= sanitize(product.description) %>
    <div class="price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
      <%= button_to 'Add to Cart', line_items_path(:product_id => product) %>
    </div>
  </div>
<% end %>